theme = "summit"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Hugo Tailwindcss Starter"

author = "Some Author"
copyright = "Copyright example, no rights reserved."

[params]
    name = "Summit Hugo Theme"
    description = "A image-heavy theme for Hugo, build with Tailwindcss."

    github_user = "octaflop"
    github_repo = "https://github.com/octaflop/summit"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
